// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file or deployment platform.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Singleton — prevents "Multiple GoTrueClient instances" warning
const SINGLETON_KEY = '__supabase_client__';
declare global { interface Window { [SINGLETON_KEY]?: SupabaseClient<Database> } }

function getClient(): SupabaseClient<Database> {
  if (typeof window !== 'undefined' && window[SINGLETON_KEY]) {
    return window[SINGLETON_KEY]!;
  }
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  if (typeof window !== 'undefined') window[SINGLETON_KEY] = client;
  return client;
}

export const supabase = getClient();